// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qrxlwqmulfznexdzmrdh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFyeGx3cW11bGZ6bmV4ZHptcmRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxNzc1MDAsImV4cCI6MjA3MDc1MzUwMH0.od7WAeo3GiO-20_8Bczl4KCUKqontkZtx37eDkLCaUw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});